### ISSUE TITLE
how to specify project, build, name

### ISSUE THREAD

**Issue by bdefore** [browserstack/automate-node-samples#9]
Per the documentation here: https://www.browserstack.com/automate/capabilities, I see there are `project`, `build`, and `name` properties but if I specify them in the `desiredCapabilities` they do not appear to have any affect on the sessions that are triggered.

**Comment by vedharish** [comment]
The BrowserStack specific capabilities should be placed on the same level as 'browserstack.user' and 'browserstack.key'. Here is an example of settings.js in nightwatch examples.

"desiredCapabilities": {
        "browserName": "firefox",
        "javascriptEnabled": true,
        "acceptSslCerts": true,
        "build": "build",
        "project": "project",
        "name": "name",
        "browserstack.user": "USERNAME",
        "browserstack.key": "KEY"
      }

The 'project', 'build', 'name' capabilities affects how the particular builds are grouped or placed on the BrowserStack automate dashboard. All the tests with the same 'build' string will be grouped together.

Note - nightwatch overrides the 'name' capability with the actual name of your test.

I am going to close this. Revert back for any more issues.

**Comment by bdefore** [comment]
thanks @vedharish i got it to work with that info. is there any way to stop nightwatch from overriding the 'name'?

**Comment by vedharish** [comment]
The desiredCapabilities can be overridden from within the tests as shown [here](https://github.com/nightwatchjs/nightwatch/blob/969e985f35df8c67cb0cff8a824530cae11515ec/tests/sampletests/simple/sample.js#L3). These wont be further overridden.

**Comment by phucgame** [comment]
Dear,
I got the same problem but for Jenkins trigger Browserstack running Cypress. 
I don't know how to Viewing test report in Jenkins.
Browserstack is using browserstack.json for configuration instead. So I don't know how to set exactly parameter to run.

The note that reference: 

Warning: Please make sure to use BROWSERSTACK_BUILD_NAME environment variable to set build name in your test code. If you don’t use BROWSERSTACK_BUILD_NAME the plugin will not be able to embed reports in Jenkins. Refer Using Environment variables section on how to use environment variables.

https://www.browserstack.com/docs/automate/selenium/jenkins?ref=jenkins_plugin#JenkinsUI

please help !!!

Thanks

**Comment by alwaysshiftingleft** [comment]
since BROWSERSTACK_BUILD_NAME is coming from Jenkins plugin, this needs to be provided as part of Jenkins pre build step
![image](https://user-images.githubusercontent.com/111993669/186924513-c4b011cf-a3cd-47dd-bdac-6b9a8d53e9d3.png)
Also you need to add the BrowserStack Cypress Test Report as post build step...
![image](https://user-images.githubusercontent.com/111993669/186924753-35c64177-d0e2-4c33-bd4d-a972d7ffcc23.png)

this will solve your problem as of now, I am also trying to send this value from the code and talking to Browserstack folks. The Cypress reports will match the Build name with the Browserstack Jenkins plugin Build name which is not the same when passed from Browserstack.json

**Comment by SachinMadhavan** [comment]
@phucgame It seems you are referring to an incorrect documentation. For Cypress tests running from Jenkins, you can refer the below. Make sure you follow all the steps and it should work for you.

https://www.browserstack.com/docs/automate/cypress/ci-cd-overview/jenkins
